import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = 'http://localhost:8000';
type Ticket = {id:string; ticket_number:string; customer_email:string; order_id?:string; category:string; subject:string; description:string; priority:string; status:string; assigned_agent_id?:string; created_at:string; updated_at:string};
type Message = {id:string; sender_name:string; message:string; message_type:string; created_at:string};
type Event = {id:string; actor_name:string; event_type:string; old_value?:string; new_value?:string; created_at:string};
type Agent = {id:string; name:string; email:string; role:string};
type Detail = Ticket & {messages:Message[]; events:Event[]};
const statuses=['OPEN','IN_PROGRESS','WAITING_FOR_CUSTOMER','WAITING_FOR_PROVIDER','RESOLVED','CLOSED'];
const priorities=['LOW','MEDIUM','HIGH','URGENT'];
const categories=['INSTALLATION','ACTIVATION','CONNECTIVITY','ORDER','TOPUP','REFUND','OTHER'];
const title=(v:string)=>v.replaceAll('_',' ');
const formatDate=(v:string)=>new Date(v).toLocaleString([], {month:'short', day:'numeric', hour:'numeric', minute:'2-digit'});

async function request(path:string, init?:RequestInit){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...init}); if(!r.ok) throw new Error(await r.text()); return r.json();}

function App(){
  const [tickets,setTickets]=useState<Ticket[]>([]); const [agents,setAgents]=useState<Agent[]>([]); const [selected,setSelected]=useState<Detail|null>(null); const [view,setView]=useState<'list'|'create'>('list'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [filters,setFilters]=useState({search:'',status:'',priority:'',category:'',assigned_agent_id:''});
  const load=()=>{setLoading(true); const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v) as [string,string][]).toString(); Promise.all([request('/tickets?'+query),request('/agents')]).then(([t,a])=>{setTickets(t.items);setAgents(a);setError('')}).catch(()=>setError('Could not load tickets')).finally(()=>setLoading(false));};
  useEffect(load,[filters.status,filters.priority,filters.category,filters.assigned_agent_id]);
  const openTicket=(id:string)=>request('/tickets/'+id).then(setSelected).catch(()=>setError('Could not load ticket'));
  return <div className="app"><header><div className="brand"><span className="mark">B</span><span>Badi Support</span></div><nav><button className={view==='list'?'active':''} onClick={()=>{setView('list');setSelected(null)}}>Tickets</button><button className={view==='create'?'active':''} onClick={()=>{setView('create');setSelected(null)}}>New ticket</button></nav></header><main>{error&&<div className="error">{error}</div>}{selected?<TicketDetail ticket={selected} agents={agents} onBack={()=>{setSelected(null);load()}} onRefresh={()=>openTicket(selected.id)}/>:view==='create'?<CreateTicket onCreated={(id)=>{setView('list');openTicket(id);load()}}/>:<TicketList tickets={tickets} agents={agents} filters={filters} setFilters={setFilters} loading={loading} onSearch={load} onOpen={openTicket}/>}</main></div>
}

function TicketList({tickets,agents,filters,setFilters,loading,onSearch,onOpen}:{tickets:Ticket[];agents:Agent[];filters:any;setFilters:any;loading:boolean;onSearch:()=>void;onOpen:(id:string)=>void}){return <section><div className="page-head"><div><p className="eyebrow">Support workspace</p><h1>Tickets</h1></div><span className="count">{tickets.length} shown</span></div><div className="filters"><input placeholder="Search tickets" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} onKeyDown={e=>e.key==='Enter'&&onSearch()}/><Select value={filters.status} onChange={(v)=>setFilters({...filters,status:v})} options={statuses} placeholder="Status"/><Select value={filters.priority} onChange={(v)=>setFilters({...filters,priority:v})} options={priorities} placeholder="Priority"/><Select value={filters.category} onChange={(v)=>setFilters({...filters,category:v})} options={categories} placeholder="Category"/><select value={filters.assigned_agent_id} onChange={e=>setFilters({...filters,assigned_agent_id:e.target.value})}><option value="">All agents</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>{loading?<div className="state">Loading tickets…</div>:tickets.length===0?<div className="state">No tickets found.</div>:<div className="ticket-table"><div className="table-head"><span>Ticket</span><span>Customer</span><span>Category</span><span>Priority</span><span>Status</span><span>Updated</span></div>{tickets.map(t=><button className="ticket-row" key={t.id} onClick={()=>onOpen(t.id)}><span><strong>{t.ticket_number}</strong><b>{t.subject}</b></span><span>{t.customer_email}</span><span>{title(t.category)}</span><span><Badge value={t.priority}/></span><span><Badge value={t.status}/></span><span className="muted">{formatDate(t.updated_at)}</span></button>)}</div>}</section>}

function TicketDetail({ticket,agents,onBack,onRefresh}:{ticket:Detail;agents:Agent[];onBack:()=>void;onRefresh:()=>void}){const [text,setText]=useState('');const [internal,setInternal]=useState(false);const [saving,setSaving]=useState(false); useEffect(()=>{const ws=new WebSocket(API.replace('http','ws')+'/ws/tickets/'+ticket.id);ws.onmessage=e=>{const data=JSON.parse(e.data);if(data.event==='new_message') onRefresh()};return()=>ws.close()},[ticket.id]); const update=(body:any)=>{setSaving(true);request('/tickets/'+ticket.id,{method:'PATCH',body:JSON.stringify(body)}).then(onRefresh).finally(()=>setSaving(false))}; const send=()=>{if(!text.trim())return;setSaving(true);request('/tickets/'+ticket.id+'/messages',{method:'POST',body:JSON.stringify({message:text,type:internal?'INTERNAL_NOTE':'AGENT_REPLY',sender_name:'Support agent'})}).then(()=>{setText('');onRefresh()}).finally(()=>setSaving(false))};return <section><button className="back" onClick={onBack}>← Tickets</button><div className="detail-head"><div><p className="eyebrow">{ticket.ticket_number}</p><h1>{ticket.subject}</h1><p className="muted">{ticket.customer_email}{ticket.order_id&&` · ${ticket.order_id}`}</p></div><div className="controls"><Select value={ticket.status} onChange={v=>update({status:v})} options={statuses}/><Select value={ticket.priority} onChange={v=>update({priority:v})} options={priorities}/><select value={ticket.assigned_agent_id||''} onChange={e=>update({assigned_agent_id:e.target.value||null})}><option value="">Unassigned</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div></div><div className="detail-grid"><div><div className="conversation"><h2>Conversation</h2><p className="description">{ticket.description}</p>{ticket.messages.map(m=><div className={'message '+(m.message_type==='INTERNAL_NOTE'?'note':'')} key={m.id}><div><strong>{m.sender_name}</strong>{m.message_type==='INTERNAL_NOTE'&&<span className="note-label">Internal note</span>}<span className="muted">{formatDate(m.created_at)}</span></div><p>{m.message}</p></div>)}</div><div className="composer"><textarea placeholder={internal?'Add an internal note':'Write a customer reply'} value={text} onChange={e=>setText(e.target.value)}/><div className="composer-foot"><label><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/> Internal note</label><button className="primary" disabled={saving||!text.trim()} onClick={send}>Send</button></div></div></div><aside><h2>Activity</h2>{ticket.events.length===0?<p className="muted">No activity yet.</p>:ticket.events.map(e=><div className="event" key={e.id}><strong>{title(e.event_type)}</strong><span>{e.old_value||'—'} → {e.new_value||'—'}</span><small>{e.actor_name} · {formatDate(e.created_at)}</small></div>)}</aside></div></section>}

function CreateTicket({onCreated}:{onCreated:(id:string)=>void}){const [form,setForm]=useState({customer_email:'',order_id:'',category:'CONNECTIVITY',subject:'',description:'',priority:'MEDIUM'});const [saving,setSaving]=useState(false);const submit=(e:React.FormEvent)=>{e.preventDefault();setSaving(true);request('/tickets',{method:'POST',body:JSON.stringify(form)}).then(t=>onCreated(t.id)).finally(()=>setSaving(false))};return <section className="form-page"><button className="back" onClick={()=>history.back()}>← Tickets</button><p className="eyebrow">New ticket</p><h1>Create support ticket</h1><form onSubmit={submit}><label>Customer email<input required type="email" value={form.customer_email} onChange={e=>setForm({...form,customer_email:e.target.value})}/></label><label>Order ID<input value={form.order_id} onChange={e=>setForm({...form,order_id:e.target.value})}/></label><div className="form-row"><label>Category<Select value={form.category} onChange={v=>setForm({...form,category:v})} options={categories}/></label><label>Priority<Select value={form.priority} onChange={v=>setForm({...form,priority:v})} options={priorities}/></label></div><label>Subject<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="primary" disabled={saving}>Create ticket</button></form></section>}

function Select({value,onChange,options,placeholder}:{value:string;onChange:(v:string)=>void;options:string[];placeholder?:string}){return <select value={value} onChange={e=>onChange(e.target.value)}>{placeholder&&<option value="">{placeholder}</option>}{options.map(o=><option key={o} value={o}>{title(o)}</option>)}</select>}
function Badge({value}:{value:string}){return <span className={'badge '+value.toLowerCase()}>{title(value)}</span>}
createRoot(document.getElementById('root')!).render(<App/>);

